# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Document\User\User:
            algorithm: bcrypt

    providers:
        database_user:
            id: 'provider.user'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        view_area:
            pattern: ^/
            anonymous: true
            security: true
            provider: database_user
            form_login:
                login_path: app_view_security_security_login
                check_path: login_check
                default_target_path: homepage
            logout:
                path: logout
                target: app_view_security_security_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
