# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    odm.hot.dbal:
       class: ODM\DBAL
       arguments:
           - "%database.hot.host%"
           - "%database.hot.port%"
           - "%database.hot.name%"

    odm.cold.dbal:
       class: ODM\DBAL
       arguments:
           - "%database.cold.host%"
           - "%database.cold.port%"
           - "%database.cold.name%"

    odm.hot.data.mapper.factory:
       class: ODM\DocumentMapper\DataMapperFactory
       arguments:
           - "@odm.hot.dbal"
       public: true

    odm.cold.data.mapper.factory:
       class: ODM\DocumentMapper\DataMapperFactory
       arguments:
           - "@odm.cold.dbal"

    model.security:
       class: AppBundle\Model\Security\SecurityModel
       arguments:
           - '@security.password_encoder'
           - '@security.token_storage'
           - '@session'
       public: true

    provider.user:
       class: AppBundle\Security\UserProvider
       arguments:
           - '@odm.hot.data.mapper.factory'
       public: true