parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

# odm start =========================================================

    odm.dbal:
       class: ODM\DBAL
       arguments:
           - "%database.hot.host%"
           - "%database.hot.port%"
           - "%database.hot.name%"
       public: false

    odm.data.mapper.factory:
       class: ODM\DocumentMapper\DataMapperFactory
       arguments:
           - "@odm.dbal"

# odm finish ========================================================


# user provider start ===============================================

    provider.user:
       class: AppBundle\Security\UserProvider
       arguments:
           - '@odm.data.mapper.factory'

# user provider finish ==============================================


# model start =======================================================

    model.security:
       class: AppBundle\Model\Security\SecurityModel
       arguments:
           - '@security.password_encoder'
           - '@security.token_storage'
           - '@session'

    model.blacklist.description:
       class: AppBundle\Model\BlackList\DescriptionModel
       arguments:
           - '@odm.data.mapper.factory'

    model.blacklist.person:
       class: AppBundle\Model\BlackList\PersonModel
       arguments:
           - '@odm.data.mapper.factory'

    model.blacklist.phone:
       class: AppBundle\Model\BlackList\PhoneModel
       arguments:
           - '@odm.data.mapper.factory'

    model.city:
       class: AppBundle\Model\City\CityModel
       arguments:
           - '@odm.data.mapper.factory'

    model.community.parse:
       class: AppBundle\Model\Community\ParseModel
       arguments:
           - '@odm.data.mapper.factory'

    model.community.publish:
       class: AppBundle\Model\Community\PublishModel
       arguments:
           - '@odm.data.mapper.factory'

    model.note:
       class: AppBundle\Model\Note\NoteModel
       arguments:
           - '@odm.data.mapper.factory'

    model.user:
       class: AppBundle\Model\User\UserModel
       arguments:
           - '@odm.data.mapper.factory'

# model finish ======================================================