logout:
    path: /logout

view.black_list:
    resource: "@AppBundle/Controller/View/BlackList/BlackListController.php"
    type:     annotation
    prefix: '/black-list/records'

view.city:
    resource: "@AppBundle/Controller/View/City/CityController.php"
    type:     annotation
    prefix: '/cities'

view.parse_list:
    resource: "@AppBundle/Controller/View/ParseList/ParseListController.php"
    type:     annotation
    prefix: '/parse-list/records'

view.parse_list.source:
    resource: "@AppBundle/Controller/View/ParseList/SourceController.php"
    type:     annotation
    prefix: '/parse-list/records/{record_id}/sources'

view.publish_list:
    resource: "@AppBundle/Controller/View/PublishList/PublishListController.php"
    type:     annotation
    prefix: '/publish-list/records'

view.note:
    resource: "@AppBundle/Controller/View/Note/NoteController.php"
    type:     annotation

view.security:
    resource: "@AppBundle/Controller/View/Security/SecurityController.php"
    type:     annotation

view.user:
    resource: "@AppBundle/Controller/View/User/UserController.php"
    type:     annotation

